name: Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '36 */6 * * *'
  push:


jobs:
   Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Deps installation
        run: |
          poetry run python -m pip install -U pip setuptools
          poetry install --only main
      - name: Run
        env:
          POSTGRES_USER: pykancha
          POSTGRES_HOST: 20.193.246.189
          POSTGRES_DB: stockscraper
          POSTGRES_PORT: 7249
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          # Make scraping random times
          if [ $(($RANDOM % 50)) == 0 ]; then exit 0; fi
          poetry run python main.py nyse
          poetry run python main.py dowjones30
          poetry run python main.py nasdaq100
          poetry run python main.py sandp500
          poetry run python export.py
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'schedule'
        with:
          files: |
            data/database.sqlite
            data/data.csv
