name: Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "36 */6 * * *"
  push:

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Deps installation
        run: |
          python -m pip install -r requirements.txt
      - name: Run
        env:
          POSTGRES_USER: pykancha
          POSTGRES_HOST: 20.193.246.189
          POSTGRES_DB: stockscraper
          POSTGRES_PORT: 7249
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          # Make scraping happen at random times
          if [ $(($RANDOM % 50)) == 0 ]; then exit 0; fi
          python main.py nyse -v
          sleep 3s;
          python export.py
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: github.event_name == 'schedule'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Scraped Data"
          files: |
            data/database.sqlite
            data/data.csv
