name: Tests

on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Deps installation
        run: |
          poetry run python -m pip install -U pip setuptools
          poetry install --only main
          poetry run python -m pip install pytest
      - name: Run Tests
        run: |
          poetry run pytest -vvv
